spring.application.name=guiasdespacho
server.port=8080

# Configuracion base de datos
spring.datasource.url=${DBURL}
spring.datasource.username=${DBUSERNAME}
spring.datasource.password=${DBPASSWORD}
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.OracleDialect

# Configuraciones JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Configuraciones HikariCP
spring.datasource.hikari.connection-test-query=SELECT 1 FROM DUAL
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.max-lifetime=1800000
spring.datasource.hikari.pool-name=HikariPool

# Session config
spring.session.jdbc.initialize-schema=always
spring.sql.init.mode=always
spring.sql.init.platform=oracle

# Configuracion de login de AWS
logging.level.software.amazon.awssdk=DEBUG
logging.level.io.awspring.cloud=DEBUG

# Importar variables de entorno desde archivo .env para despliegue local
spring.config.import=optional:file:.env[.properties]